unittest/solver_factory.hpp
unittest/test_solvers.cpp

- creation of a solver factory for all the available solvers.
- update the test_solvers.cpp using the factory, this should remove the segfault from the gepgitlab build farm.

update the unittests of the solver using a solver factory

---

.travis/build-and-test.sh
examples/CMakeLists.txt

Follows #660 
While here, I saw that other python files in `examples/notebook/*.py` ; shouldn't we also run those as tests ?
@imaroger had issues with `cartpole_swing_up.py`.

Run examples as tests

---

bindings/python/crocoddyl/core/integrator/euler.hpp
bindings/python/crocoddyl/core/solver-base.hpp
include/crocoddyl/core/solver-base.hpp
src/core/integrator/euler.cpp
src/core/solver-base.cpp
src/core/solvers/ddp.cpp
src/core/utils/callbacks.cpp

This PR:
1. defines getter and setter functions which are needed for c++ implementation,
2. changes copy_const_reference instead of return_by_value (Python binding returned policy), 
3. returns the const block in Euler integrator, and
4. fixes an issue in the Euler python bindings (wrong returning of data.dx)
@PepMS thanks for reporting the needed of these getter functions

Added getter and setter functions for solvers + improved Python bindings

---

bindings/python/crocoddyl/utils/__init__.py
examples/arm_manipulation.py
src/multibody/contacts/multiple-contacts.cpp
unittest/bindings/test_actions.py

This PR fixes a couple issues when working with floating-base systems based on `DifferentialFwdDynamicsDerived` and adds a unit test for it.
- Fixes a bug related to `nq`,`nv` (swapped; difference when the floating base uses quaternion)
- Uses the correct `tau` vector to pass to ABA (the actuation->tau should be passed rather than the raw control vector)
- Adds a unit test with the Anymal robot using a floating base
- Fixes the arm_manipulation example visualisation
- Minor typos

Fix bug, add unittest for floating-base DifferentialFwdDynamicsDerived

---

src/multibody/actions/free-fwddyn.cpp

ForwardKin is not needed after aba or computeAllTerms

[DAMFreefwddyn] remove redundant forwardKin call

---

src/core/utils/callbacks.cpp

The reduction ocst where printed in the wrong order for the callbackverbose() case 2.

[bug] callback case 2

---

CMakeLists.txt

This fixes CI. Until upstream CMake is fixed we need to block any further syncing of the CMake submodule. This also warrants a new patch release.
cc: @nim65s @proyan 
This reverts commit cf179f7bcd676cc8a489add1e83f4c031c9f09d0.

Revert "[CMake] sync submodule"

---

bindings/python/crocoddyl/utils/quadruped.py

This error appears only for Debug mode, since the quaternion malformation actives a Pinocchio assert (in `pinocchio::diff`).
It solves the issue #693.

Malformation of quaternon in quadrupedal formulation

---

src/core/solvers/fddp.cpp

I believe this should be `terminalModel` as the running models all get updated with the for-loop below.
I checked with the biped and quadruped examples and there was no difference in the logs for convergence. In practice, I don't believe this to have too much of an impact but this should be the correct behaviour.

FDDP: Fix expectedImprovement for terminalModel

---

include/crocoddyl/core/data/actuation.hpp
include/crocoddyl/multibody/data/contacts.hpp
include/crocoddyl/multibody/data/impulses.hpp
include/crocoddyl/multibody/data/multibody.hpp
include/crocoddyl/multibody/numdiff/cost.hxx
unittest/factory/pinocchio_model.hpp
unittest/test_contacts.cpp
unittest/test_costs.cpp

Currently, the cost num-diff class uses the residual vector to retrieve second order derivatives.
This is method is OK if we use the quadratic activation model. We need to work on the numerical differentiation of second order derivatives.
To be able to test the second order derivatives of the cost function, I modified the unittest code in such a way that it only uses the quadratic activation model.
I have created an issue to handle this limitation later #708

Cost numdiff patch in unittest code

---

bindings/python/crocoddyl/multibody/contacts/multiple-contacts.cpp
bindings/python/crocoddyl/multibody/impulses/multiple-impulses.cpp
include/crocoddyl/multibody/contacts/multiple-contacts.hpp
include/crocoddyl/multibody/contacts/multiple-contacts.hxx
include/crocoddyl/multibody/impulses/multiple-impulses.hpp
include/crocoddyl/multibody/impulses/multiple-impulses.hxx
unittest/test_multiple_contacts.cpp
unittest/test_multiple_impulses.cpp

This PR extends the API to handle the contact / impulse status, however, **it is still back compatible with previous code**. The rationality behind this modification is as follows
"_If we need to re-assign new set of contacts (or impulses), then we need to create the multi-contact(-impulse) data again and this is not convenient for MPC applications_"
To avoid this, we need to allocate the contact (or impulse) data for all possible contacts (or impulses) as global mechanism allocation. Then, we process the corresponding contacts (or impulses) giving its status (active or inactive).
Finally, the PR includes extra unittest regarding this modification.

Included status information of contacts / impulses (active / inactive)

---

bindings/python/crocoddyl/__init__.py
bindings/python/crocoddyl/core/solver-base.cpp
bindings/python/crocoddyl/utils/__init__.py
bindings/python/crocoddyl/utils/biped.py
bindings/python/crocoddyl/utils/quadruped.py
examples/bipedal_walk.py
examples/bipedal_walk_ubound.py
examples/boxfddp_vs_boxddp.py
examples/humanoid_manipulation.py
examples/humanoid_manipulation_ubound.py
examples/humanoid_taichi.py
examples/quadrupedal_gaits.py
examples/quadrupedal_walk_ubound.py
include/crocoddyl/core/solver-base.hpp
src/core/solver-base.cpp

In Crocoddyl, there is a clear division between problem and solvers and the following functions (inside the solver abstraction) do not respect it:
- `solver.get_models()`,
- `solver.get_datas()`,
furthermore, they are also unnecessary (and make confusion) because both models and datas can be retrieved through shooting problem, e.g.
```cpp
solver.get_problem()->get_runningDatas();
```
or (in Python)
```python
solver.problem.runningDatas
```
To make the library consistent, the PR cleans the examples and unittest code. Additionally, it removes the duplicated functions in the solver abstraction.

Retrieve models and solvers only through shooting-problem iface

---

bindings/python/crocoddyl/core/optctrl/shooting.cpp
include/crocoddyl/core/optctrl/shooting.hpp
include/crocoddyl/core/optctrl/shooting.hxx

This PR proposes a function that
- updates the model of a i node, and
- allocates data for that node.
This additional function is useful for MPC application, when we might want to replace the action model.

Function to update a model for a given node

---

doc/feasible_ddp.tex

Previous description of KKT matrix was wrong because the Lagrangian lacked the constraint on initial state, dx0 = f0. This leads to only T Lagrangian multiplicators lambda whereas there should have T+1 of them.

Correct KKT matrix

---

bindings/python/crocoddyl/multibody/contacts/multiple-contacts.cpp
bindings/python/crocoddyl/multibody/costs/cost-sum.cpp
bindings/python/crocoddyl/multibody/impulses/multiple-impulses.cpp
include/crocoddyl/multibody/contacts/multiple-contacts.hpp
include/crocoddyl/multibody/contacts/multiple-contacts.hxx
include/crocoddyl/multibody/costs/cost-sum.hpp
include/crocoddyl/multibody/costs/cost-sum.hxx
include/crocoddyl/multibody/impulses/multiple-impulses.hpp
include/crocoddyl/multibody/impulses/multiple-impulses.hxx
unittest/CMakeLists.txt
unittest/factory/cost.cpp
unittest/factory/cost.hpp
unittest/test_cost_sum.cpp
unittest/test_multiple_contacts.cpp
unittest/test_multiple_impulses.cpp

This PR includes the cost status as proposed in #720.
As mentioned in previous pull request, the idea behind of this is to have a global mechanism allocation.
Additionally, this PR includes unittest code for cost sum.
**Note the changes of this PR are still back compatible with previous code.**

Included status information of costs (active / inactive)

---

include/crocoddyl/core/activation-base.hpp

Added templatized activation declaration, which was missing in the following line:
https://github.com/loco-3d/crocoddyl/blob/cdac522ec37a885f559794ef57c3244e70926621/include/crocoddyl/core/activation-base.hpp#L67

Templatized activation data

---

unittest/test_actions.cpp
unittest/test_activations.cpp
unittest/test_contacts.cpp
unittest/test_costs.cpp
unittest/test_diff_actions.cpp
unittest/test_impulses.cpp
unittest/test_solvers.cpp
unittest/test_states.cpp

This PR uses `boost::test_tools::output_test_stream` to print properly the message that shows all the unittest cases.
It helps the developers to understand the unittest cases.

Printing a message that shows all the unittest cases

---

bindings/python/crocoddyl/core/state-base.cpp
bindings/python/crocoddyl/core/state-base.hpp
include/crocoddyl/core/state-base.hxx

This PR enables the limits `has_limits` whenever it has been defined at least one upper / lower bounds. Additionally, it allows us to write internal data for Python code.

State bounds: proper enabling of limits + writing internal data of lb / ub

---

bindings/python/crocoddyl/multibody/contacts/multiple-contacts.cpp
bindings/python/crocoddyl/multibody/costs/cost-sum.cpp
bindings/python/crocoddyl/multibody/impulses/multiple-impulses.cpp
include/crocoddyl/multibody/contacts/multiple-contacts.hpp
include/crocoddyl/multibody/contacts/multiple-contacts.hxx
include/crocoddyl/multibody/costs/cost-sum.hpp
include/crocoddyl/multibody/costs/cost-sum.hxx
include/crocoddyl/multibody/impulses/multiple-impulses.hpp
include/crocoddyl/multibody/impulses/multiple-impulses.hxx
unittest/test_cost_sum.cpp
unittest/test_multiple_contacts.cpp
unittest/test_multiple_impulses.cpp

The warning messages includes the name of the cost, contact or impulse items. This helps the users to debug their own code.
Additionally, the PR updates the expected warning messages in the unittest code.

Improved the warning messages in cost-sum, contact and impulse

---

bindings/python/crocoddyl/__init__.py
bindings/python/crocoddyl/utils/biped.py
bindings/python/crocoddyl/utils/pendulum.py
bindings/python/crocoddyl/utils/quadruped.py
examples/arm_manipulation.py
examples/bipedal_walk.py
examples/bipedal_walk_ubound.py
examples/boxfddp_vs_boxddp.py
examples/double_pendulum.py
examples/humanoid_manipulation.py
examples/humanoid_manipulation_ubound.py
examples/humanoid_taichi.py
examples/notebooks/arm_manipulation.ipynb
examples/notebooks/bipedal_walking.ipynb
examples/notebooks/introduction_to_crocoddyl.ipynb
examples/quadrotor.py
examples/quadrotor_ubound.py
examples/quadrupedal_gaits.py
examples/quadrupedal_walk_ubound.py
include/crocoddyl/multibody/actions/contact-fwddyn.hxx
include/crocoddyl/multibody/actions/impulse-fwddyn.hxx
include/crocoddyl/multibody/contacts/multiple-contacts.hxx
include/crocoddyl/multibody/costs/cost-sum.hxx
include/crocoddyl/multibody/impulses/multiple-impulses.hxx

This PR parses the current active set of contacts (or impulses) to carry computations on the contact (or impulse) dynamics. This was the last piece of cake needed to follow the idea of global allocation of data.
Additionally, there are other general improvements:
- sorted the active cost, contact and impulse vectors for easier reading.
- used numpy array inside gepetto display for efficiency (and numpy matrix is tagged as deprecated)
- created a display abstract for including other display methods
- added meshcat displayer and integrated in couple of Jupyter notebooks (it needs to include force, frame trajectory and friction cone display).
- used numpy array in all examples and notebooks.

Using active contact and impulses in actions + other minor improvements

---

bindings/python/crocoddyl/core/optctrl/shooting.cpp
include/crocoddyl/core/action-base.hpp
include/crocoddyl/core/action-base.hxx
include/crocoddyl/core/actions/diff-lqr.hpp
include/crocoddyl/core/actions/diff-lqr.hxx
include/crocoddyl/core/actions/lqr.hpp
include/crocoddyl/core/actions/lqr.hxx
include/crocoddyl/core/actions/unicycle.hpp
include/crocoddyl/core/actions/unicycle.hxx
include/crocoddyl/core/diff-action-base.hpp
include/crocoddyl/core/diff-action-base.hxx
include/crocoddyl/core/integrator/euler.hpp
include/crocoddyl/core/integrator/euler.hxx
include/crocoddyl/core/optctrl/shooting.hpp
include/crocoddyl/core/optctrl/shooting.hxx
include/crocoddyl/multibody/actions/contact-fwddyn.hpp
include/crocoddyl/multibody/actions/contact-fwddyn.hxx
include/crocoddyl/multibody/actions/free-fwddyn.hpp
include/crocoddyl/multibody/actions/free-fwddyn.hxx
include/crocoddyl/multibody/actions/impulse-fwddyn.hpp
include/crocoddyl/multibody/actions/impulse-fwddyn.hxx
unittest/test_actions.cpp
unittest/test_diff_actions.cpp

This PR includes few extra functions for easily updating models and datas that are convenient for MPC applications:
-  extra constructor that allows user to pass the datas
- `updateNode`: update the node information (two methods, one of them allocates data)
- `circularAppend`: emulate a `push_back` routine of a circular_buffer. This solution was discussed in #772.
Additionally, this PR includes:
- a function to check that the data is consistent with the model,
- doxygen documentation of the `ShootingProblem` members,
- a clean-up of the `ActionModelAbstractTpl` class, and
- a missed virtual keywords

Extra functions in the ShootingProblem class to easily update models and datas

---

README.md
bindings/python/crocoddyl/core/optctrl/shooting.cpp
bindings/python/crocoddyl/core/solver-base.cpp
bindings/python/crocoddyl/core/solvers/ddp.cpp
doc/Doxyfile.extra.in
include/crocoddyl/core/optctrl/shooting.hpp
include/crocoddyl/core/optctrl/shooting.hxx
include/crocoddyl/core/solver-base.hpp
include/crocoddyl/core/solvers/ddp.hpp
include/crocoddyl/core/solvers/fddp.hpp
include/crocoddyl/core/state-base.hpp
include/crocoddyl/multibody/utils/quadruped-gaits.hpp
src/core/solver-base.cpp
src/core/solvers/box-ddp.cpp
src/core/solvers/box-fddp.cpp
src/core/solvers/ddp.cpp
src/core/solvers/fddp.cpp
src/core/solvers/kkt.cpp

This PR solves the issue #780 by applying the solution 1. It consists of:
1. do not performances useless matrix-matrix multiplications when `nu=0`
2. store a unique `nx`, `ndx` and `nu` in the shooting problem
3. use 2 for allocating the solver data
Additionally, there are other tasks that this PR includes:
1. Added doxygen documentation of  `SolverAbstract`, `SolverDDP` and `SolverFDDP`
2. Tiny improvement in the doxygen documentation of `StateAbstractTpl`
3. Configure doxygen to do not sort alphabetically the functions
4. Updated the REAME file (cherry-pick from `release/v1.3.0` branch)

Data allocation in solvers for contact-phase MPC applications

---

bindings/python/crocoddyl/core/diff-action-base.cpp
bindings/python/crocoddyl/multibody/contact-base.cpp
bindings/python/crocoddyl/multibody/costs/contact-force.cpp
bindings/python/crocoddyl/multibody/costs/contact-impulse.cpp
bindings/python/crocoddyl/multibody/impulse-base.cpp
include/crocoddyl/core/activations/quadratic-barrier.hpp
include/crocoddyl/core/diff-action-base.hpp
include/crocoddyl/core/optctrl/shooting.hxx
include/crocoddyl/multibody/contact-base.hpp
include/crocoddyl/multibody/contact-base.hxx
include/crocoddyl/multibody/contacts/multiple-contacts.hxx
include/crocoddyl/multibody/impulse-base.hpp
include/crocoddyl/multibody/impulse-base.hxx
include/crocoddyl/multibody/impulses/multiple-impulses.hxx

These "set-to-zero-force" changes doesn't affect the computation performed by the solvers. However, for conciseness, it is a good idea to set force and their derivatives to zero.
Additionally, the PR fixes a bug in the definition of the terminal node in `ShootingProblem::updateNode`.

Set inactive forces and their derivatives to zero + DAM documentation + fixed bug in updateNode

---

bindings/python/crocoddyl/core/actuation/actuation-squashing.cpp
bindings/python/crocoddyl/core/state-base.cpp

It turns out that there was only a single place that we were not including the eigenpy header. This hopefully should fix the issue #795. @gfadini could you try this branch and report if this fixes your issue?

Included eigenpy header to avoid memory leak

---

bindings/python/crocoddyl/core/numdiff/diff-action.cpp
bindings/python/crocoddyl/core/optctrl/shooting.cpp
bindings/python/crocoddyl/core/solver-base.cpp
bindings/python/crocoddyl/crocoddyl.cpp
bindings/python/crocoddyl/multibody/contacts/multiple-contacts.cpp
bindings/python/crocoddyl/multibody/costs/cost-sum.cpp
bindings/python/crocoddyl/multibody/impulses/multiple-impulses.cpp
bindings/python/crocoddyl/utils/__init__.py
bindings/python/crocoddyl/utils/map-converter.hpp
bindings/python/crocoddyl/utils/vector-converter.hpp

This PR fixes the memory leak produced in the Python interface reported in #795.
I have test myself that there is no more memory leaks in vector and map converters.
To validate it, I used the following code:
```python
import numpy as np
import crocoddyl
import pinocchio
import example_robot_data
import time
def test1():
model = crocoddyl.ActionModelUnicycle()
model.r = [10,1]
u0 = np.array([0., 0.])
x0 = np.array([-1., -1., 1.])
data = model.createData()
duration = 0.
while duration < 10.:
t0 = time.time()
problem = crocoddyl.ShootingProblem(x0, [model] * 10, model, [data] * 10, data)
ddp = crocoddyl.SolverDDP(problem)
ddp.solve([x0] * 11, [u0] * 10, 1)
ddp.xs
tf = time.time()
duration += tf - t0
def test3():
talos_arm = example_robot_data.loadTalosArm()
robot_model = talos_arm.model …
```

Fix memory leaks in vector and map converters #795

---

bindings/python/crocoddyl/core/action-base.cpp
bindings/python/crocoddyl/core/action-base.hpp
bindings/python/crocoddyl/core/activation-base.cpp
bindings/python/crocoddyl/core/activation-base.hpp
bindings/python/crocoddyl/core/actuation-base.cpp
bindings/python/crocoddyl/core/actuation-base.hpp
bindings/python/crocoddyl/core/diff-action-base.cpp
bindings/python/crocoddyl/core/diff-action-base.hpp
bindings/python/crocoddyl/multibody/contact-base.cpp
bindings/python/crocoddyl/multibody/contact-base.hpp
bindings/python/crocoddyl/multibody/cost-base.cpp
bindings/python/crocoddyl/multibody/cost-base.hpp
bindings/python/crocoddyl/multibody/costs/control.cpp
bindings/python/crocoddyl/multibody/impulse-base.cpp
bindings/python/crocoddyl/multibody/impulse-base.hpp
bindings/python/crocoddyl/utils/__init__.py
bindings/python/crocoddyl/utils/pendulum.py
unittest/bindings/test_actions.py
unittest/bindings/test_actuations.py
unittest/bindings/test_contacts.py
unittest/bindings/test_costs.py
unittest/bindings/test_force_cost.py
unittest/bindings/test_impulse_com_cost.py
unittest/bindings/test_impulses.py
unittest/bindings/test_shooting.py
unittest/bindings/test_solvers.py
unittest/bindings/test_squashing.py
unittest/bindings/test_states.py

This PR solves the issue #799 for all the type of models:  action, diff-action, actuation, activation, cost, contact and impulses.
It also updated the unittest code by defining a `createData` function for each case that it needs. Finally, it rewrites this code to use numpy array.
@gfadini you might want to try this stuff.
@nmansard, @proyan, @PepMS, @wxmerkt, @julesser fyi. You need to be aware that it is possible to create a data structure in Python. For more details see the changes inside `__init__.py`

Enable createData for Python derived classes

---

bindings/python/crocoddyl/utils/pendulum.py

Couldn't compile devel with python 3 otherwise.

[Python] remove debug with wrong syntax

---

benchmark/arm_manipulation_optctrl.py
benchmark/bipedal_walk_optctrl.py
benchmark/quadrupedal_gaits_optctrl.py

Changes in #808 introduced a rename in a Python derived class. This class is using in the arm_manipulation.py as well.
I noticed that the quadrupedal benchmark is not running, i.e. this fails:
```bash
make -s benchmarks-py-quadrupedal_gaits_optctrl
```
However, I decided to do not modify since there are important changes in #809. @proyan could you check this command in your PR?

Update benchmarks given changes in the Python unittest

---

include/crocoddyl/multibody/actuations/floating-base.hpp
include/crocoddyl/multibody/states/multibody.hxx
unittest/test_codegen.cpp

This PR includes missing typedef needed to compile `test_codegen`. Additionally, there is an additional issue that seems to be related with https://github.com/stack-of-tasks/pinocchio/pull/1255.
For completeness this is the compilation error that I encountered:
```
In file included from /usr/local/include/eigen3/Eigen/Core:427:0,
from /usr/local/include/pinocchio/utils/cast.hpp:8,
from /usr/local/include/pinocchio/fwd.hpp:23,
from /usr/local/include/pinocchio/spatial/fwd.hpp:9,
from /usr/local/include/pinocchio/multibody/model.hpp:9,
from /usr/local/include/pinocchio/parsers/urdf.hpp:9,
from /home/cmastalli/devel/crocoddyl/unittest/test_codegen.cpp:9:
/usr/local/include/eigen3/Eigen/src/Core/functors/AssignmentFunctors.h: In instantiation of ‘void Eigen::internal::assign_op<DstScalar, …
```

Fixed test_codegen

---

include/crocoddyl/multibody/actions/contact-fwddyn.hxx
include/crocoddyl/multibody/actions/free-fwddyn.hxx
unittest/factory/diff_action.cpp
unittest/factory/diff_action.hpp
unittest/test_diff_actions.cpp

This PR fixes an issue coming from #809. This happens disappear due to lack of unittest code.
So this PR also includes the needed unittest code.
Before merging this PR, I would like to discuss the possibility of removing the memory allocation in `quasiStatic`. The benefits of doing that is we could parallelize this routine. Indeed, I am interested in create a `quasiStatic` methon inside `ShootingProblem`.
@proyan do you have any concern with it?

Fixing quasiStatic for cases where we have inactive contacts

---

bindings/python/crocoddyl/utils/quadruped.py

For some reason, this deprecated function was not updated during #821.

Removed a use of a deprecated code in Python

---

.travis.yml
bindings/python/crocoddyl/core/optctrl/shooting.cpp
examples/bipedal_walk.py
examples/bipedal_walk_ubound.py
examples/boxfddp_vs_boxddp.py
examples/humanoid_manipulation.py
examples/humanoid_manipulation_ubound.py
examples/humanoid_taichi.py
examples/quadrupedal_gaits.py
examples/quadrupedal_walk_ubound.py
include/crocoddyl/core/action-base.hxx
include/crocoddyl/core/optctrl/shooting.hpp
include/crocoddyl/core/optctrl/shooting.hxx
include/crocoddyl/multibody/actions/contact-fwddyn.hpp
include/crocoddyl/multibody/actions/contact-fwddyn.hxx
include/crocoddyl/multibody/actions/free-fwddyn.hpp
include/crocoddyl/multibody/actions/free-fwddyn.hxx
unittest/CMakeLists.txt
unittest/factory/diff_action.hpp
unittest/test_problem.cpp

This PR proposes a multithreading support for computing the quasi-static commands along a state trajectory. This function helps us to compute faster a warm-start.
To do so, we need to define data for the `quasiStatic` functions defined in free / contact forward dynamics.
Note that the `ShootingProblem::quasiStatic` is bound in Python.

quasiStatic with multithreading support

---

bindings/python/crocoddyl/core/diff-action-base.cpp
bindings/python/crocoddyl/core/diff-action-base.hpp
bindings/python/crocoddyl/crocoddyl.cpp
include/crocoddyl/core/diff-action-base.hpp
include/crocoddyl/core/diff-action-base.hxx

After #809, we could derive `quasiStatic` function of differential action models as well. However, the mentioned PR did not include the Python bindings for this case.

 Missed bindings for the quasiStatic function in differential action models

---

bindings/python/crocoddyl/core/optctrl/shooting.cpp
bindings/python/crocoddyl/core/solver-base.cpp
bindings/python/crocoddyl/core/solvers/ddp.cpp
bindings/python/crocoddyl/core/solvers/fddp.cpp
include/crocoddyl/core/optctrl/shooting.hpp
include/crocoddyl/core/optctrl/shooting.hxx
include/crocoddyl/core/solver-base.hpp
include/crocoddyl/multibody/friction-cone.hxx
src/core/solver-base.cpp
unittest/python/crocoddyl/solver.py

This caught me out again hard :cry:. I checked and I believe this was the last `assert_pretty` that could have unintended consequences.
assert_pretty is silent in Release mode. Passing in a wrong-sized xs/us
will be copied and messes up the entire memory resulting in optimisation
rubbish. Moving these checks to if / throw_pretty resolves this issue.

SolverAbstract: Throw exception if the candidate xs/us have the wrong dimensions

---

include/crocoddyl/multibody/actions/free-fwddyn.hxx

These changes are addressing the misbehavior of ```SolverBoxFDDP``` and ```SolverBoxDDP``` shown in #849

Adding the effort limits to FreeForwardDynamics

---

bindings/python/crocoddyl/core/solvers/ddp.cpp
include/crocoddyl/core/solvers/ddp.hpp
src/core/solvers/ddp.cpp

This comes from a problem that is documented here: https://gitlab.laas.fr/aparag/warmStart/-/blob/master/unicycle/Feasible%20warmstart.ipynb
If the solver is being started with isFeasible=False. This boolean is only updated to true when you make a full step. And if for some reason, this doesn't happen (which normally should not occur), this boolean remains False. We don't set this boolean on the basis of the gaps. we set it on the basis of the user input.

[solver/ddp] if gaps are zero, solution is feasible

---

include/crocoddyl/core/optctrl/shooting.hxx
src/core/solvers/box-ddp.cpp
src/core/solvers/box-fddp.cpp
src/core/solvers/ddp.cpp
src/core/solvers/fddp.cpp
src/core/solvers/kkt.cpp
unittest/factory/action.cpp
unittest/factory/action.hpp
unittest/factory/solver.cpp
unittest/test_solvers.cpp

This PR deals with a bug introduced with #787 . 
All ddp (and derived classes) objects that depend on the action model nu (e.g. `ddp.k`, `ddp.Qu` etc) are stored in an std::vector<>. This std::vector is initialized with each object having a size nu_max (number of rows or number of cols). 
In the `ddp.solve()`, we are assigning to these objects directly from the problem models. For e.g., in https://github.com/loco-3d/crocoddyl/blob/devel/src/core/solvers/ddp.cpp#L221, `Qu` (which is size `nu_max`) is being assigned to an object `d->Lu` (which is size `nu`). Since `nu_max`> `nu`, we haven't had any segfaults yet. But this is problematic implementation.
This PR fixes this bug. 
TODO: 
~~1) Box-DDP and Box-FDDP solvers~~
~~2) KKT solver~~
~~3) add multiple nu action models in unittests~~

DDP objects change size when the actionmodels.nu size < nu_max. Fix this bug

---

bindings/python/crocoddyl/core/cost-base.cpp
bindings/python/crocoddyl/core/cost-base.hpp
bindings/python/crocoddyl/core/costs/cost-sum.cpp
include/crocoddyl/core/cost-base.hpp
include/crocoddyl/core/costs/cost-sum.hpp

This PR basically cleans up a bit the code:
- fixed minor things in the documentation
- used throw_pretty in the Python bindings of cost-base (as done in other cases)
- simplified a bit more the code (nothing dramatic)

Cleaned up and fixed minor issues in the documentiobn of cost related classes

---

benchmark/bipedal-timings.cpp
bindings/python/crocoddyl/multibody/actions/contact-fwddyn.cpp
include/crocoddyl/multibody/actions/contact-fwddyn.hpp
include/crocoddyl/multibody/actions/contact-fwddyn.hxx
unittest/factory/diff_action.cpp
unittest/factory/diff_action.hpp

Hello,
This PR is related to issue #884. 
Changes:
- `DifferentialActionModelContactFwdDynamics` is type agnostic.
- benchmark/bipedal-timings.cpp was modified as it didn't have the `#include` floating base actuation model flag and was causing a compilation error due to change to `DifferentialActionModelContactFwdDynamics`.
- One unittest was added to test for `DifferentialActionModelContactFwdDynamics` with a `ActuationModelFull` instance (TalosArm is used for the test)

DifferentialActionModelContactFwdDynamics type agnostic

---

src/core/solvers/ddp.cpp

The #848 introduces an automatic way of detecting if the gaps are zero.
If so, then the algorithm switches to a feasibility mode (i.e., runs DDP or Box-DDP).
The problem with #848 is that the introduced gap threshold was defined without taking care of the different examples.
If you inspect how the logs are changed, you will see that the humanoid problems switch to feas=1 from the first iteration.
To be concise, I would discuss only the taichi case.
After #848, then the solver behaviour changes to:
```bash
iter 	 cost 	      stop 	    grad 	  xreg 	      ureg 	 step 	 feas
0  1.78178e+02  3.25380e+01  6.16363e+02  1.00000e-08  1.00000e-08   0.0039     1
1  1.78178e+02  9.28629e+03  1.18098e+03  1.00000e-07  1.00000e-07   0.0020     1
2  1.78178e+02  9.35243e+03  1.21551e+03  1.00000e-06 …
```

Fixed bug: the gap threshold was too big

---

bindings/python/crocoddyl/multibody/cop-support.cpp
bindings/python/crocoddyl/multibody/friction-cone.cpp
bindings/python/crocoddyl/multibody/wrench-cone.cpp
include/crocoddyl/core/activations/quadratic-barrier.hpp
include/crocoddyl/core/fwd.hpp
include/crocoddyl/core/optctrl/shooting.hxx
include/crocoddyl/multibody/cop-support.hpp
include/crocoddyl/multibody/cop-support.hxx
include/crocoddyl/multibody/frames.hpp
include/crocoddyl/multibody/friction-cone.hpp
include/crocoddyl/multibody/friction-cone.hxx
include/crocoddyl/multibody/wrench-cone.hpp
include/crocoddyl/multibody/wrench-cone.hxx
unittest/factory/cost.cpp
unittest/test_cop_support.cpp
unittest/test_diff_actions.cpp
unittest/test_friction_cone.cpp
unittest/test_wrench_cone.cpp

Since we are explicitly declaring the copy constructor for the frames, we need to also explicitly declare the assignment operator. This becomes a warning in more recent versions of gcc/C++ standards.

Fix deprecated copy for frames

---

CMakeLists.txt
unittest/factory/cost.cpp
unittest/test_actions.cpp
unittest/test_activations.cpp
unittest/test_actuation.cpp
unittest/test_boxqp.cpp
unittest/test_contact_costs.cpp
unittest/test_contacts.cpp
unittest/test_cop_support.cpp
unittest/test_costs.cpp
unittest/test_costs_noFF.cpp
unittest/test_diff_actions.cpp
unittest/test_friction_cone.cpp
unittest/test_impulse_costs.cpp
unittest/test_multiple_contacts.cpp
unittest/test_multiple_impulses.cpp
unittest/test_problem.cpp
unittest/test_solvers.cpp
unittest/test_states.cpp
unittest/test_wrench_cone.cpp
unittest/unittest_common.hpp

This PR replace `isMuchSmallerThan` by `isZero` in all the unit-tests. Additionally, it changes the tolerance in numdiff tests by `10 * sqrt(eps)` where `eps` is the numdiff disturbance. We need to include `10` as a factor since the Talos contact-dynamics unit-tests needed. Finally, this PR increases the tolerance by `1e-9` in some extra unit-tests.

Used isZero in unit-tests

---

bindings/python/crocoddyl/multibody/costs/control-gravity-contact.cpp
bindings/python/crocoddyl/multibody/costs/control-gravity.cpp
include/crocoddyl/core/numdiff/cost.hpp
include/crocoddyl/core/numdiff/cost.hxx
include/crocoddyl/multibody/costs/control-gravity-contact.hpp
include/crocoddyl/multibody/costs/control-gravity-contact.hxx
include/crocoddyl/multibody/costs/control-gravity.hpp
include/crocoddyl/multibody/costs/control-gravity.hxx
include/crocoddyl/multibody/numdiff/contact.hpp
include/crocoddyl/multibody/numdiff/contact.hxx
unittest/factory/actuation.cpp
unittest/factory/actuation.hpp
unittest/factory/contact_cost.cpp
unittest/factory/cost.cpp
unittest/factory/cost.hpp
unittest/factory/pinocchio_model.cpp
unittest/factory/pinocchio_model.hpp
unittest/test_contacts.cpp
unittest/test_costs.cpp
unittest/test_costs_noFF.cpp

This PR handles the comments that I left in https://github.com/loco-3d/crocoddyl/pull/888#pullrequestreview-588392158 plus a few extra improvements of both cost functions: control gravity and control gravity contact. Concretely, these is the list of actions:
1. Remove unnecessary computation regarding the actuation model.
2. Adapted the unittest and cost / contact numdiff routines for properly testing 1.
3. Deprecated constructors as they don't need to pass the actuation model.
4. Fixed the residual computation (i.e., r = tau - g(q) rather than r = g(q) - tau)
Let me give you explanations for each point. First, it is not needed to pass the actuation model as the actuation data is stored by the action models as designed choice (point 1). Second, I believe you guys got confused as the …

Removed unnecessary computation and fixed residual in control gravity costs

---

bindings/python/crocoddyl/crocoddyl.cpp
bindings/python/crocoddyl/multibody/actuations/multicopter-base.cpp
examples/quadrotor.py
examples/quadrotor_ubound.py
include/crocoddyl/multibody/actuations/multicopter-base.hpp
unittest/factory/actuation.cpp

This PR removes an unnecessary argument (i.e., n_rotors) in the multicopter actuation API. Note that this information can be extracted by the mapping matrix. Additionally, it adds checks useful for debugging mode. Finally, it fixes a tiny issue in the unittest.
Note that the PR deprecates the current constructor. @PepMS (fyi)

Improved multicopter actuation API + fixed unittest

---

.github/workflows/industrial_ci_action.yml
.travis.yml
dependencies.rosinstall
include/crocoddyl/core/activations/smooth-abs.hpp

This adds a GitHub Actions-based CI on 18.04 and 20.04 resolving Pinocchio/EigenPy via ROS and using catkin tools to build and run tests on Crocoddyl. Part of the motivation is that a) Travis is being phased out, b) Crocoddyl can and is being used within ROS workspaces e.g. for robot deployment, and c) that RobotPkg without staging fails CI jobs every now and then when packages are out of sync (e.g. in #932 and #931 right now). This augments the more extensive coverage and set of configurations Gepgitlab is providing and is more of a stand-in replacement for Travis.

Add GitHub Actions CI with ROS dependency resolution

---

bindings/python/crocoddyl/__init__.py
bindings/python/crocoddyl/core/action-base.cpp
bindings/python/crocoddyl/core/diff-action-base.cpp
bindings/python/crocoddyl/core/integrator/euler.cpp
bindings/python/crocoddyl/core/optctrl/shooting.cpp
bindings/python/crocoddyl/multibody/actions/contact-fwddyn.cpp
bindings/python/crocoddyl/multibody/actions/free-fwddyn.cpp
bindings/python/crocoddyl/multibody/actions/impulse-fwddyn.cpp
bindings/python/crocoddyl/multibody/actuations/floating-base.cpp
include/crocoddyl/core/action-base.hpp
include/crocoddyl/core/action-base.hxx
include/crocoddyl/core/diff-action-base.hpp
include/crocoddyl/core/diff-action-base.hxx
include/crocoddyl/core/integrator/euler.hpp
include/crocoddyl/core/integrator/euler.hxx
include/crocoddyl/core/optctrl/shooting.hpp
include/crocoddyl/core/optctrl/shooting.hxx
include/crocoddyl/multibody/actions/contact-fwddyn.hpp
include/crocoddyl/multibody/actions/contact-fwddyn.hxx
include/crocoddyl/multibody/actions/impulse-fwddyn.hpp
include/crocoddyl/multibody/actions/impulse-fwddyn.hxx
src/core/solvers/ddp.cpp
src/core/solvers/fddp.cpp

This PR includes:
1. `operator<<` for shooting problem, action model, and differential action model to enable `print(ddp.problem)` or `print(ddp.running_models[t])` which is useful in debugging to get information on the problem
2. Removes the ineffective OpenMP simd instructions previously pointed out by Justin and also notified by the clang compiler as not optimised
3. Fixes the `MeshcatVisualizer` when using the latest Pinocchio devel branch (not sure when it broke)

ostream operators, MeshcatVisualizer fix, removal of ineffective SIMD reduction

---

CMakeLists.txt
unittest/test_actuation.cpp

We have a lot of conversions between `Eigen::Index` and `std::size_t` (e.g. `.head(nu)` etc.) which pollute the compiler output. Fixing those would make part of the code quite unreadable. Instead, this PR activates all warnings and then only turns off `Wsign-conversion`. The remaining warning is fixed.

Activate all warnings; turn off Wsign-conversion

---

bindings/python/crocoddyl/core/core.cpp
bindings/python/crocoddyl/core/core.hpp
bindings/python/crocoddyl/core/utils/stop-watch.cpp
bindings/python/crocoddyl/core/utils/stop-watch.hpp
include/crocoddyl/core/utils/Stdafx.hh
include/crocoddyl/core/utils/stop-watch.hpp
src/core/solvers/ddp.cpp
src/core/utils/stop-watch.cpp

I've added a stop-watch class which is very useful for doing accurate profiling of the code. This is important for the work that I plan to do to optimize the performance of Crocoddyl with high-order integration schemes. Profiling is off by default so that it does not affect computation times.

Add stop-watch class (with Python bindings) for profiling code.

---

bindings/python/crocoddyl/crocoddyl.cpp

Hotfix for exposing std::vector<MatrixXdRowMajor>

---

CMakeLists.txt
examples/CMakeLists.txt

Currently we have a configuration option that can break build: `cmake .. -DBUILD_PYTHON_INTERFACE=OFF` will still try to build the Python examples. This PR fixes this.

Only build Python-examples if bindings are built

---

.github/workflows/industrial_ci_action.yml
.travis.yml
package.xml
unittest/bindings/test_shooting.py

This PR addresses two items:
1. Execution of unit tests on the ROS-CI running on GitHub Actions. In turn, allows failures on Travis which is prone to spurious failures (thus reverts #948)
2. Updates the cmake submodule to include a packaging fix (https://github.com/jrl-umi3218/jrl-cmakemodules/pull/479) important for use of Crocoddyl in downstream projects 
Resolves #944

Run unittests in ROS-CI, deactivate Travis-CI

---

bindings/python/crocoddyl/CMakeLists.txt

To avoid the need for python users to set `LD_LIBRARY_PATH` when the `CMAKE_INSTALL_PREFIX` is not a standard one.
ref. https://github.com/stack-of-tasks/eigenpy/pull/241

[CMake] set INSTALL_RPATH for python on linux

---

bindings/python/crocoddyl/core/solver-base.cpp
bindings/python/crocoddyl/core/solver-base.hpp
include/crocoddyl/core/solver-base.hpp
include/crocoddyl/core/solvers/ddp.hpp
include/crocoddyl/core/solvers/fddp.hpp
src/core/solver-base.cpp
src/core/solvers/ddp.cpp

This PR proposes
1. Improve the documentation of the DDP, FDDP and Solver abstraction
2. Allocate temporal for internally storing the dynamic feasibility
3. Wrap dV, dVexp in Python
4.  Remove the setting of`is_feasible` in `computeDynamicFeasibility` (it could affect any solver that relies on it)

Few improvements in the solvers

---

bindings/python/crocoddyl/core/utils/stop-watch.cpp
include/crocoddyl/core/optctrl/shooting.hxx
include/crocoddyl/core/solver-base.hpp
include/crocoddyl/core/utils/stop-watch.hpp
src/core/solvers/box-ddp.cpp
src/core/solvers/ddp.cpp
src/core/solvers/fddp.cpp
src/core/utils/stop-watch.cpp

This PR proposes a method for enabling at runtime the profiler. This will be something like this:
```c++
getProfiler().enable_profiler();
\\ run algorithm
getProfiler().report_all();
```
or
```python
crocoddyl.enable_profiler()
crocoddyl.stop_watch_report(5)
```
This simplifies at lot the performance analysis.
Additionally, this PR includes other macros for profiling DDP, FDDP and BoxDDP solvers.

Enable profiler at runtime

---

include/crocoddyl/core/controls/poly-two-rk4.hxx

Hey @andreadelprete!
I noticed we have an error in the computation of `c[1]`, which it is fixed in this PR.
Additionally, this fixes the numerical-convergence issues on the MPC algorithm which I reported to you.
Thanks for sharing your notes.
I will later (no in this PR) work on RK3 integrator and its parametrization.

Fixed computation of coefficient in  poly-two-rk4 parametrization

---

include/crocoddyl/multibody/residuals/contact-friction-cone.hpp
include/crocoddyl/multibody/residuals/contact-friction-cone.hxx
unittest/factory/diff_action.cpp
unittest/factory/diff_action.hpp
unittest/factory/state.cpp
unittest/factory/state.hpp
unittest/test_residuals.cpp

In reference of #986 problem, and as an update to #1000 I have found some time to add changes in order to accommodate previous mistakes and requests. It was decided to use new branch for cleaner history (I couldn't merge newest changes from develop without an additional merge commit).  I am using the newest Eigen 3.4 release for matrix multiplication. 
Notes to have in mind: 
1. This solution still only works for xz plane for now, I have tested it with my implementation of a test-stand, it works ok
2. In `unittest/factory/diff_action.cpp` I have not added force regularization when testing with friction (force regularization is not implemented yet for 2D contact) 
3. In `include/crocoddyl/multibody/residuals/contact-friction-cone.hpp` I dont have a cast for ImpulseData for 2D contact since …

[Update] Manage 2d contact friction in xz plane

---

bindings/python/crocoddyl/multibody/contacts/contact-1d.cpp
bindings/python/crocoddyl/multibody/multibody.cpp
bindings/python/crocoddyl/multibody/multibody.hpp
include/crocoddyl/multibody/contacts/contact-1d.hpp
include/crocoddyl/multibody/contacts/contact-1d.hxx
include/crocoddyl/multibody/fwd.hpp
include/crocoddyl/multibody/residuals/contact-force.hpp
include/crocoddyl/multibody/residuals/contact-force.hxx
unittest/factory/contact.cpp
unittest/factory/contact.hpp
unittest/test_contacts.cpp

Implementation of a contact model 1D that constrains only the translation along z-axis . It allows to apply a normal force while moving tangentially, which is useful for e.g. scraping or sanding tasks, but not allowed by current contact models (2D, 3D, 6D). 
More specifically : 
- implementation of ContactModel1D 
- completion the contacts unittests factory 
- implemention of python binding
- completion of ResidualModelContactForce to allow normal force cost
I'm not sure if things are missing, please let me know !

Add ContactModel1D

---

.github/workflows/industrial_ci_action.yml

#1015 passed CI which is using g++ but fails under clang. This PR adds a clang config to GitHub Actions CI to catch this in the future
Note: We are expecting the clang build to fail, as https://github.com/loco-3d/crocoddyl/runs/4721070535 did

[CI] Add config for 20.04 with clang

---

include/crocoddyl/core/actions/lqr.hpp
include/crocoddyl/core/actions/lqr.hxx
include/crocoddyl/core/costs/residual.hxx
src/core/solvers/kkt.cpp

- CostModelResidual: Workaround for heap allocation in the product with the diagonal weighting matrix of the activation. This is a workaround for https://gitlab.com/libeigen/eigen/-/issues/2408
- LQR: Introduces a temporary variable for the Hessian-vector product to eliminate temporaries in the computation of the cost

Reduce temporary allocations

---

include/crocoddyl/core/utils/exception.hpp

This fix applies to later versions of C++ compilers. I checked on my machine for GCC 11.2 & clang 13 installed through apt, clang 12 installed through conda.
I think this is related to backwards compatibility for recent versions of GCC, where now the iostream header might required for cout and cin

Fix compiler error due to unincluded iostream

---

bindings/python/crocoddyl/core/state-base.cpp
bindings/python/crocoddyl/core/state-base.hpp

I have added a setter for nq, nx, ndx, nv which will enable the user to change the state dimensions when creating a state class by inheriting statemultibody class.
Further, I have added a fix in the JIntegrateTransport binding.

[state] added a setter  and fixed a bug in JIntegrateTransport

---

CMakeLists.txt

Per Element chat - example-robot-data is required for unittests, benchmarking, and examples. If all three options are OFF, we don't need to add this required dependency

Make example-robot-data an optional dependency

---

unittest/CMakeLists.txt

This PR provides a similar solution proposed in https://github.com/humanoid-path-planner/hpp-fcl/pull/270.
Hopefully, this PR will fix the segfault that appears in Debian systems.

Tests: remove link to boost unit test framework

---

bindings/python/crocoddyl/core/solvers/box-qp.cpp
include/crocoddyl/core/solvers/box-qp.hpp
src/core/solvers/box-qp.cpp
unittest/test_boxqp.cpp

This error in the condition can be triggered with random initialisations.
In our Box-DDP/FDDP solvers, triggering this error is less likely to happen.
But, in that case, we could expect to run many useless iterations.
This should also improve the computation time of those solvers.

Fixed Armijo condition in BoxQP

---

bindings/python/crocoddyl/__init__.py
bindings/python/crocoddyl/core/constraints/constraint-manager.cpp
include/crocoddyl/core/numdiff/action.hxx
include/crocoddyl/core/numdiff/constraint.hxx
include/crocoddyl/core/numdiff/diff-action.hxx
include/crocoddyl/multibody/actions/contact-fwddyn.hxx
src/core/solvers/ddp.cpp

The minor changes are:
- Resized the constraint data in numdiff classes (needed when the dimension changes).
- Used `with_custodian_and_ward_postcall` in Python bindings of resize function.
- Defined profiler of Vx computation
- Cosmetic changes in the quasiStatic function of contact fwddyn action.
All these changes have been reviewed in #1080, however, I am splitting this PR into pieces so it is easier to inspect the code.

Added meshcat as displayer + minor changes

---

bindings/python/crocoddyl/core/core.cpp
bindings/python/crocoddyl/core/core.hpp
bindings/python/crocoddyl/core/data/joint.cpp
bindings/python/crocoddyl/core/residuals/joint-acceleration.cpp
bindings/python/crocoddyl/core/residuals/joint-torque.cpp
bindings/python/crocoddyl/multibody/data/contacts.cpp
bindings/python/crocoddyl/multibody/data/multibody.cpp
include/crocoddyl/core/data/joint.hpp
include/crocoddyl/core/fwd.hpp
include/crocoddyl/core/residuals/joint-acceleration.hpp
include/crocoddyl/core/residuals/joint-acceleration.hxx
include/crocoddyl/core/residuals/joint-torque.hpp
include/crocoddyl/core/residuals/joint-torque.hxx
include/crocoddyl/multibody/actions/contact-fwddyn.hpp
include/crocoddyl/multibody/actions/contact-fwddyn.hxx
include/crocoddyl/multibody/actions/free-fwddyn.hpp
include/crocoddyl/multibody/actions/free-fwddyn.hxx
include/crocoddyl/multibody/data/contacts.hpp
include/crocoddyl/multibody/data/multibody.hpp
include/crocoddyl/multibody/fwd.hpp
unittest/factory/diff_action.cpp
unittest/factory/pinocchio_model.cpp
unittest/factory/pinocchio_model.hpp
unittest/factory/state.cpp
unittest/factory/state.hpp
unittest/test_contacts.cpp
unittest/test_impulses.cpp

This collector allows to define cost and constraint for joint torque and generalised acceleration across different formulations: forward vs inverse dynamics.
In this PR, we integrated and unit-tested this feature for forward-dynamics formulations only. However, I will later create a PR that integrates these stuffs for inverse-dynamics formulations. Note that I have decided to split this into different PRs, so it easier to review, merge and provide feedback.
Edit: as a plus, I also created an unit-test for the Hector quadrotor.

Introduced the notion of joint data collector

---

bindings/python/crocoddyl/fwd.hpp
unittest/factory/cost.cpp
unittest/factory/cost.hpp
unittest/factory/residual.cpp
unittest/factory/residual.hpp

The main change is as follows:
*unittest : use GeometryObject's CollisionGeometryPtr typedef* (4f6f3e4aa42fd1c93a19ccd06100bac60cf62d12)
Which makes the factory code independent on whether installed release of Pinocchio (or hpp-fcl) uses std or boost shared_ptr.

Fix unittest factory for future compatibility

---

include/crocoddyl/multibody/actions/free-fwddyn.hpp

Fix for what seems to be inconsistent matrix sizes in free-fwddyn : `Minv` is `nv x nv` while `u_drift` and `dtau_dx` have `nu` rows.

Fix size bug in free-fwddyn 

---

src/core/solvers/ddp.cpp
src/core/solvers/fddp.cpp
src/core/solvers/intro.cpp

In nixpkgs, we encountered [the following error](https://logs.ofborg.org/?key=nixos/nixpkgs.232585&attempt_id=a548c3a7-18fe-4568-a125-8c820509a67d) on aarch64-linux when bumping to 2.0.0:
```bash
/build/source/src/core/solvers/intro.cpp:196:19: error: no matching function for call to 'max(double&, int)'
196 |   stop_ = std::max(hfeas_, abs(d_[0] + 0.5 * d_[1]));
```
The obvious fix is to replace `abs` with `std::abs`.

Fix build on aarch64-linux

---

CMakeLists.txt
bindings/python/crocoddyl/multibody/frames.cpp

This PR changes a couple of CMake configuration options (I needed the changes to compile against a conda environment. We should wait for the CI to tell us if it breaks on non-conda setups).
* use find-external FindOpenMP.cmake
* include the pinocchio/fwd.hpp header in bindings multibody/frames.cpp (this might be required under pin3x or something)
* ~use `add_project_dependency` for OpenMP instead of `find_package`, for other CMake projects consuming crocoddyl (e.g. sobec)~

cmake: use find-external FindOpenMP.cmake

---

CMakeLists.txt
unittest/factory/pinocchio_model.cpp
unittest/factory/pinocchio_model.hpp
unittest/factory/state.cpp
unittest/test_codegen.cpp

`EXAMPLE_ROBOT_DATA_MODEL_DIR` is now a compile definition
draft: gitlab-ci is expected to fail until the end of a robotpkg rebuild + CI images regenerations.
PS: I should have made 4.1.0 instead of 4.0.7, sorry for that.

update to example-robot-data 4.0.7

---

include/crocoddyl/core/residuals/joint-acceleration.hpp
include/crocoddyl/core/residuals/joint-acceleration.hxx
include/crocoddyl/multibody/residuals/state.hxx
unittest/test_residuals.cpp

Fixed set_reference in state residual

---

include/crocoddyl/multibody/residuals/pair-collision.hxx

Hello,  
First, I'd like to thank you for your work. Here's what I think a small mistake in pair-collision.hxx I corrected. 
This pull request updates a conditional statement to use `collisionPairs.size()` instead of `ngeoms` because ngeoms is not the number of collision pairs but the number of geometry objects in geom_model. 
The number of pairs can be higher than the number of geometry objects, hence this pull request.
- Replaced `static_cast<pinocchio::FrameIndex>(geom_model->ngeoms)` with `static_cast<pinocchio::FrameIndex>(geom_model->collisionPairs.size())` in the condition.
After building it, I tried on a small example in python and it works. I did not run unit tests after this but it builds successfully. Please, do not hesitate to tell me if I did something wrong here.
None
Thank …

Bug Fix : pair-collision.hxx, changing the method to check the pair_id with collisionPair.size()

---

include/crocoddyl/core/action-base.hpp
include/crocoddyl/core/diff-action-base.hpp

The current API does not set the action model bounds as emphasized in #1170 . This PR fixes this bug by making the corresponding getters virtual .

Fix getters for constraint bounds

---

bindings/python/crocoddyl/core/core.cpp
bindings/python/crocoddyl/core/core.hpp
bindings/python/crocoddyl/core/utils/exception.hpp
bindings/python/crocoddyl/core/utils/excepton.cpp
include/crocoddyl/core/utils/exception.hpp
src/core/utils/exception.cpp

This feature is needed when we wish to catch an exception in Python triggered by Crocoddyl.

Included Python bindings for Crocoddyl exceptions

---

bindings/python/crocoddyl/CMakeLists.txt

Stub generation is broken :
- The stub generator is launched in the wrong directory
- The stub generator don't depend of the binding and then can be launched before

Fix stub generation

---

CHANGELOG.md
include/crocoddyl/core/activations/quadratic-barrier.hpp
unittest/test_activations.cpp

This PR fixes the issue mentioned in #1129.
Now when one of the `ub` or the `lb` are `nan` or `inf`, once they are converted to `std::numeric_limits<Scalar>::max()/min()`, such bounds are no longer modified even when a valid value for `beta` is specified. 
Thanks to @traversaro, an associated test function is added to the existing `test_activations.cpp` file, which fails when the bounds are not respected, as in the former code.

Fixing the violation of bounds when one of the bounds is `inf` in `ActivationModelQuadraticBarrier`

---

CHANGELOG.md
bindings/python/crocoddyl/multibody/actuations/floating-base-propellers.cpp
bindings/python/crocoddyl/multibody/multibody.cpp
bindings/python/crocoddyl/multibody/multibody.hpp
examples/quadrotor_fwddyn.py
examples/quadrotor_invdyn.py
examples/quadrotor_ubound.py
include/crocoddyl/core/numdiff/actuation.hpp
include/crocoddyl/core/numdiff/actuation.hxx
include/crocoddyl/multibody/actuations/floating-base-propellers.hpp
include/crocoddyl/multibody/actuations/floating-base-thrusters.hpp
include/crocoddyl/multibody/actuations/multicopter-base.hpp
include/crocoddyl/multibody/fwd.hpp
unittest/bindings/test_copy.py
unittest/factory/actuation.cpp
unittest/factory/actuation.hpp
unittest/factory/diff_action.cpp
unittest/test_actuation.cpp
unittest/test_residuals.cpp

This PR introduces a new actuation model that encapsulates floating base systems equipped with propellers in their base. This class replaces our previous actuation model for multi-copters, which was designed to pass a torque-mapping matrix. This old design is unintuitive and hard codes that propellers are oriented along the robot's z-axis in inverse dynamics formulations.
In a nutshell, we can model easily other types of systems such as marine robots.
Apart from this new model, the PR includes:
- Deprecation of the multi-copter actuation model
- Unit test for this new actuation model
- Examples based on this new model
In future, I plan to extend this actuation to cases where the propellers are placed in the robot's limbs. For an efficient implementation, this will require changes in the …

Introduced floating base propeller actuation model

---

include/crocoddyl/multibody/actuations/floating-base-thrusters.hpp

The changed line of code tried to call a templated member for an [Eigen fixed-size block expression](https://eigen.tuxfamily.org/dox/group__TutorialBlockOperations.html) but instead calls the dynamic-sized overload.
This created a compile issue with Eigen 3.3.7 and clang 16.0.6.

Fix use of 'template' when actually calling non-template member

---

CHANGELOG.md
bindings/python/crocoddyl/__init__.py

Fixed Rviz display

---

CHANGELOG.md
bindings/python/crocoddyl/__init__.py
examples/notebooks/solutions/cartpole_analytical_derivatives.py

These errors are reported in the gitlab-ci.

Fixed yapf reported errors

---

CHANGELOG.md
bindings/python/crocoddyl/core/actions/diff-lqr.cpp
bindings/python/crocoddyl/core/actions/lqr.cpp
include/crocoddyl/core/actions/diff-lqr.hpp
include/crocoddyl/core/actions/diff-lqr.hxx
include/crocoddyl/core/actions/lqr.hpp
include/crocoddyl/core/actions/lqr.hxx
unittest/bindings/factory.py
unittest/bindings/test_actions.py
unittest/factory/action.cpp
unittest/factory/action.hpp
unittest/factory/diff_action.cpp
unittest/factory/diff_action.hpp
unittest/factory/solver.cpp
unittest/factory/solver.hpp
unittest/test_solvers.cpp

This PR proposes the following extensions to LQR actions:
- Define constructor to pass LQR matrices and vectors
- Introduce `Random` function to generate random LQR problems
- Add a check procedure for inspecting if the cost hessian is s.d.f. (i.e., convex optimization problem)
-  Deprecate set/get functions to avoid users defining nonconvex problems
- Add C++ and Python unit tests with random LQR models
- Include equality and inequality linear constraints
- Improve documentation
In short, the LQR actions are now useful beyond unit testing. Users can build LQR problems much more easily.

Extending LQR actions

---

CHANGELOG.md
bindings/python/crocoddyl/core/actions/diff-lqr.cpp
bindings/python/crocoddyl/core/actions/lqr.cpp
include/crocoddyl/core/actions/diff-lqr.hpp
include/crocoddyl/core/actions/diff-lqr.hxx
include/crocoddyl/core/actions/lqr.hpp
include/crocoddyl/core/actions/lqr.hxx

This PR cleans up a few inconsistencies from the previous PR #1261:
- Errors in the documentation
- Missed Python bindings of LQR constructors
- Bug in the calc function for computing equality constraints

LQR clean ups

---

CHANGELOG.md
include/crocoddyl/multibody/wrench-cone.hxx

If merged. this PR will fix some bugs with the `WrenchCone` object, where the setters for `mu`, `min_nforce`, and `max_nforce` were not updating the member fields of the class.

Fix bug of wrench cone fields not being updated with setters

---

.pre-commit-config.yaml
CHANGELOG.md
pyproject.toml

Hi,
pre-commit CI is currently failing, because since [ruff v0.5.6](https://github.com/astral-sh/ruff/blob/main/CHANGELOG.md#056) ipython notebook files are included by default.
Ours have many issues, so this PR just disable this check to get CI green again.
While here, move one config option from pre-commit config to global config in pyproject.toml.

update ruff config

---

CHANGELOG.md
include/crocoddyl/core/solver-base.hpp
src/core/solver-base.cpp

This pull request introduces a refinement to the calculation of the inequality feasibility by adding the inequality bounds to the calculation. The update ensures that when a constraint is within its specified bounds, its feasibility is considered 0. Only if the constraint exceeds the bounds, its feasibility is greater than zero.

Add Bounds to the Inequality Feasibility Calculation

---

include/crocoddyl/multibody/actuations/floating-base-thrusters.hpp

I fixed the direction of thrust which is required for calculation of thrust jacobian. 
When the orientation of thruster is not identical to that of parent link, this patch is required.
Since rotational moment generated by thrust is $\lambda p \times u$, where $\lambda$, $p$, and $u$ are thrust, position of thruster, and direction of thrust, respectively.

[actuation] fixed thrust direction for calculation of thrust jacobian

---

CMakeLists.txt
include/crocoddyl/core/utils/stop-watch.hpp
src/core/utils/stop-watch.cpp

In this PR,
- I add to the existing profilers a more efficient version that does not repeatedly use `std::map::find`.
- I upgrade the minimum CMake version above with `cmake/find-internal/OpenMP` is used rather than the platform specific one. @ManifoldFR FYI
I can make two separate PRs if that is more convenient for you.

Provide more efficient of profilers

---

include/crocoddyl/core/utils/stop-watch.hpp
src/core/utils/stop-watch.cpp

This follows up #1334 and makes profiler have a slightly smaller overhead.

Further improve profiler.

---

CHANGELOG.md
bindings/python/crocoddyl/core/solvers/box-ddp.cpp
bindings/python/crocoddyl/core/solvers/box-fddp.cpp
bindings/python/crocoddyl/core/solvers/ddp.cpp
bindings/python/crocoddyl/core/solvers/fddp.cpp
bindings/python/crocoddyl/core/solvers/intro.cpp
bindings/python/crocoddyl/core/solvers/kkt.cpp

In Python, we return garbage when accessing an item in list of matrices without using `tolist()`. Note that this doesn't happens when using `tolist()`.
This is an issue that I believe comes from Pinocchio's new StdVec_MatrixXs bindings.
Anyways, these changes fixed the problem in Python.

Changed return policy to be compliant with Pinocchio

---

CHANGELOG.md
include/crocoddyl/multibody/actions/contact-invdyn.hpp

Hi @cmastalli this PR fixes a bug in the computation of the derivatives of the contact forces.
This bug can be observed by adding a disabled contact to the `DifferentialActionModelContactInvDynamics` class: 
```python
contactModel = crocoddyl.ContactModelMultiple(state, nu)
supportContactModel = crocoddyl.ContactModel6D(
state,
target_id,
pinocchio.SE3.Identity(),
pinocchio.LOCAL,
nu,
np.array([0, 0]),
)
contactModel.addContact("contact", supportContactModel, False)
runningModel = crocoddyl.IntegratedActionModelEuler(
crocoddyl.DifferentialActionModelContactInvDynamics(
state, actuation, contactModel, runningCosts), dt
)
```
when running `calc` and `calcDiff` it can be observed that the jacobian of the constraint `Hu` is empty as `df_du` is only updated when the contact is active.
The …

Force contacts to update force derivatives

---

CHANGELOG.md
CMakeLists.txt

I encountered the same problem as in pinocchio (https://github.com/stack-of-tasks/pinocchio/issues/2187).
I propose to fix it with the same fix https://github.com/stack-of-tasks/pinocchio/pull/2202

Remove absolute path for boost library

---

CHANGELOG.md
CMakeLists.txt

This will install libcrocoddyl.so.2.2.0 as a binary and libcrocoddyl.so as a symlink, instead of just libcrocoddyl.so as a binary.

Add install version.
