- .travis.yml
Replaces #632 
Test if this works and how much this slows down Travis/CI
Check output from fork if this works:
https://travis-ci.com/wxmerkt/crocoddyl/builds/138956994
> Update Travis to include 16.04 builds

- include/crocoddyl/core/data-collector-base.hpp
- unittest/bindings/test_force_cost.py
- unittest/bindings/test_momemtum_cost.py
- unittest/bindings/test_utils.py
- unittest/test_actions.cpp
- unittest/test_activation.cpp
- unittest/test_diff_actions.cpp
- unittest/test_impulses.cpp
- unittest/test_solvers.cpp
- unittest/test_state.cpp
This is a follow-up PR of #647 which only applies the right format.
Fyi @jcarpent, we're checking the code format for c++ and Python. You don't need to learn the code format, we use the Gepetto linter tools. See here for more information: https://github.com/loco-3d/crocoddyl/wiki/Developer-Guide
> Formatting code

- bindings/python/crocoddyl/__init__.py
- bindings/python/crocoddyl/core.hpp
- bindings/python/crocoddyl/core/solvers/box-fddp.hpp
- bindings/python/crocoddyl/utils/__init__.py
- include/crocoddyl/core/solvers/box-fddp.hpp
- src/CMakeLists.txt
- src/core/solvers/box-fddp.cpp
- src/core/solvers/fddp.cpp
This PR proposes a new solver called "Control-limited Feasibility-prone DDP" (in short box-FDDP).  box-FDDP is a novel solver that leverages feasibility together with control limits, and it has shown greater globalization than box-DDP.
The FDDP has been also improved, in particular the testing of test. It considers step when the expected improvement is 0, this happens in LQR problems. Additionally, it fixes a problem in ascent case.
Finally, I have included a coupled of functions tha saves data using Python pickle framework.
@PepMS fyi
> Control-limited FDDP solver

- bindings/python/crocoddyl/__init__.py
It parses the friction cone information (coefficient and orientation) from the models defined to the OC problem. The code displays such information only when it has been defined the friction cones.
In future work, I will need to parse also the number of edges used by the friction cone. Currently, it assumes 4 edges for all the friction cones.
Finally, by removing unnecessary creation of geometries, the display is lighter and faster.
> Add display of friction cone + created geometries only once

- bindings/python/crocoddyl/core.hpp
- bindings/python/crocoddyl/core/activations/quadratic-barrier.hpp
- bindings/python/crocoddyl/core/activations/weighted-quadratic-barrier.hpp
- include/crocoddyl/core/activations/weighted-quadratic-barrier.hpp
- src/CMakeLists.txt
- src/core/activations/weighted-quadratic-barrier.cpp
- src/core/activations/weighted-quadratic.cpp
- unittest/test_activation.cpp
It includes the c++ class, Python bindings and c++ unit-test code.
@PepMS this is for you!
> Added weighted-quadratic-barrier (activation) + cleaned up documentation

- bindings/python/crocoddyl/multibody/costs/cost-sum.cpp
- include/crocoddyl/multibody/costs/cost-sum.hpp
- include/crocoddyl/multibody/costs/cost-sum.hxx
> CostModelContainer: Make CostItem a shared_ptr

- unittest/factory/action.cpp
- unittest/factory/action.hpp
- unittest/factory/solver.cpp
- unittest/factory/solver.hpp
- unittest/test_actions.cpp
- unittest/test_contacts.cpp
- unittest/test_impulses.cpp
- unittest/test_multiple_contacts.cpp
- unittest/test_multiple_impulses.cpp
- unittest/test_solvers.cpp
This PR includes the refactored of action and solver factories used for unit-testing.
Additionally, it removes few unittest cases which are useless and buggy in other jobs.
> Refactored missing factory classes + removed useless tests in contact/impulses

- bindings/python/crocoddyl/core/actuation/actuation-squashing.cpp
- bindings/python/crocoddyl/core/core.cpp
- bindings/python/crocoddyl/core/core.hpp
- include/crocoddyl/core/actuation/actuation-squashing.hpp
- include/crocoddyl/core/fwd.hpp
- src/core/actuation/actuation-squashing.cpp
- unittest/factory/actuation.cpp
- unittest/factory/actuation.hpp
- unittest/factory/diff_action.cpp
- unittest/factory/diff_action.hpp
Actuation class to squashing any multibody actuation model with any squashing function.
> Squashing actuation

- unittest/factory/cost.cpp
- unittest/factory/cost.hpp
- unittest/test_cost_sum.cpp
The PR title is self-explained!
> Added more cost-sum unittest cases

- include/crocoddyl/multibody/actuations/multicopter-base.hpp
In #736 , @wxmerkt ask for a little explanation and references to guide the user when using the MultiCopter actuation model.
The current PR aims to give that explanation.
> [multicopter] added brief model explanation

- bindings/python/crocoddyl/multibody/contacts/multiple-contacts.cpp
- bindings/python/crocoddyl/multibody/costs/cost-sum.cpp
- bindings/python/crocoddyl/multibody/impulses/multiple-impulses.cpp
- include/crocoddyl/multibody/contacts/multiple-contacts.hpp
- include/crocoddyl/multibody/contacts/multiple-contacts.hxx
- include/crocoddyl/multibody/costs/cost-sum.hpp
- include/crocoddyl/multibody/costs/cost-sum.hxx
- include/crocoddyl/multibody/impulses/multiple-impulses.hpp
- include/crocoddyl/multibody/impulses/multiple-impulses.hxx
This PR includes a function to retrieve the inactive costs, contacts and impulses. These function are convenient for user code.
> Retrieve inactive costs, contacts and impulses

- CMakeLists.txt
I totally forgot that in  #739, sorry.
> [Cmake] use project exports

- bindings/python/crocoddyl/__init__.py
found by @olivier-stasse : https://github.com/Gepetto/gepetto-viewer-corba/issues/144
> [Python] fix wrong hardcoded windowID for gepetto gui

- README.md
Reopen #770 with the right branch as basis.
> acknoledge the robocom++ fundings

- benchmark/arm-manipulation-codegen.cpp
- benchmark/arm-manipulation-timings.cpp
- benchmark/bipedal-timings.cpp
- benchmark/bipedal-with-contact-codegen.cpp
Provides more detailed information on the benchmarks. specifically, maximum and minimum times, and std-deviation of the timings.
> benchmark update

- include/crocoddyl/core/activations/quadratic-barrier.hpp
- include/crocoddyl/core/solvers/fddp.hpp
- src/core/solvers/fddp.cpp
1) use inherited calcdiff for solver/fddp
2) fix cppad support for activation model quadratic barrier
> Minor fixes

- README.md
- examples/notebooks/whole_body_manipulation.ipynb
This PR includes a new notebook prepared for the summer MEMMO school.
@nmansard your feedback might be useful, but unfortunately, we need to merge it very soon.
@nim65s do we have time to merge this branch, and then to deploy a new Crocoddyl version?
> Added whole-body manipulation notebook

- include/crocoddyl/core/utils/deprecate.hpp
- include/crocoddyl/multibody/costs/centroidal-momentum.hpp
- include/crocoddyl/multibody/costs/com-position.hpp
- include/crocoddyl/multibody/costs/contact-force.hpp
- include/crocoddyl/multibody/costs/contact-friction-cone.hpp
- include/crocoddyl/multibody/costs/contact-impulse.hpp
- include/crocoddyl/multibody/costs/control.hpp
- include/crocoddyl/multibody/costs/frame-placement.hpp
- include/crocoddyl/multibody/costs/frame-rotation.hpp
- include/crocoddyl/multibody/costs/frame-translation.hpp
- include/crocoddyl/multibody/costs/frame-velocity.hpp
- include/crocoddyl/multibody/costs/impulse-friction-cone.hpp
- include/crocoddyl/multibody/costs/state.hpp
Hi @proyan 
These modifications should fixed the issue. However, I couldn't test it fully since there is a problem with Pinocchio.
@nim65s we should merge this into the release topic, when this PR gets approved
> c++98 compatibility of deprecate macro

- include/crocoddyl/multibody/actuations/floating-base.hpp
- include/crocoddyl/multibody/states/multibody.hxx
This PR should be a solution to #807, I still have to properly test it on some robot whose base is not FloatingBase, but it doesn't change anything if it is
> General underactuated base

- bindings/python/crocoddyl/__init__.py
- bindings/python/crocoddyl/utils/quadruped.py
Due to recent changes in the way that we retrieve list and dict introduced in #802, we need to update the viewers and quadruped plotter. Unfortunately, these needed changes were not detected due to we don't test them.
> Updated the viewer and quadruped plotter

- src/core/solver-base.cpp
From discussion in #842, we can see that the user might struggle to debug an error in the warm-start dimensions.
This PR solves this issue, @wxmerkt you might be interested to review the code.
> Check that the dimension of warm-start is correct

- bindings/python/crocoddyl/core/solvers/box-ddp.cpp
- bindings/python/crocoddyl/core/solvers/box-fddp.cpp
- bindings/python/crocoddyl/core/solvers/box-qp.cpp
- bindings/python/crocoddyl/core/solvers/ddp.cpp
- bindings/python/crocoddyl/core/solvers/fddp.cpp
- bindings/python/crocoddyl/core/solvers/kkt.cpp
- include/crocoddyl/core/action-base.hpp
This PR should solve the request in #859.
@edantec could you test it from your side?
> Register converters for shared_ptrs of solver classes

- bindings/python/crocoddyl/multibody/frames.cpp
- include/crocoddyl/multibody/frames.hpp
> Memory alignement of frame classes with boost python

- include/crocoddyl/core/optctrl/shooting.hpp
- include/crocoddyl/core/optctrl/shooting.hxx
Fix bug in shootingproblem:`updateModel`, `updateNode`
> [shootingproblem][updatenode] fix doc and node number

- bindings/python/crocoddyl/__init__.py
@cmastalli 
This is a pr to address [issue](https://github.com/loco-3d/crocoddyl/issues/896#issue-777084374) #896
> fix_corba_bad_param_issue

- include/crocoddyl/core/activations/quadratic-flat-exp.hpp
- include/crocoddyl/core/activations/quadratic-flat-log.hpp
This issue was causing problems in 16.04 jobs.
For some magical reason, this code was passing in the other jobs (@nim65s -- can you explain me why?)
@edantec this PR is important for you as it fixes issues in the flat-log/exp activation models.
> Bugfix: Created properly the data in flt-exp/log activations

- PUBLICATIONS.md
- README.md
- include/crocoddyl/core/optctrl/shooting.hxx
- unittest/test_problem.cpp
Note that if we do not modify `nthreads` in the constructor, the code crashes. This happens if we use the constructor with an externally allocated data.
> Defined nthreads in the other shooting-problem constructor + improved README file

- include/crocoddyl/multibody/actions/free-fwddyn.hpp
- include/crocoddyl/multibody/actions/free-fwddyn.hxx
As suggested by @cmastalli in #936 I have changed the name of the flag `with_armature` to `without_armature`.
> Change name of flag from with_armature to without_armature

- bindings/python/crocoddyl/__init__.py
- bindings/python/crocoddyl/core/residual-base.cpp
- bindings/python/crocoddyl/core/residual-base.hpp
- include/crocoddyl/core/costs/residual.hxx
- include/crocoddyl/core/residual-base.hpp
- include/crocoddyl/core/residual-base.hxx
- include/crocoddyl/core/residuals/control.hxx
- include/crocoddyl/multibody/residuals/centroidal-momentum.hxx
- include/crocoddyl/multibody/residuals/com-position.hxx
- include/crocoddyl/multibody/residuals/contact-control-gravity.hxx
- include/crocoddyl/multibody/residuals/contact-cop-position.hxx
- include/crocoddyl/multibody/residuals/contact-force.hxx
- include/crocoddyl/multibody/residuals/contact-friction-cone.hxx
- include/crocoddyl/multibody/residuals/contact-wrench-cone.hxx
- include/crocoddyl/multibody/residuals/control-gravity.hxx
- include/crocoddyl/multibody/residuals/frame-placement.hxx
- include/crocoddyl/multibody/residuals/frame-rotation.hxx
- include/crocoddyl/multibody/residuals/frame-translation.hxx
- include/crocoddyl/multibody/residuals/frame-velocity.hxx
- include/crocoddyl/multibody/residuals/impulse-com.hxx
- include/crocoddyl/multibody/residuals/state.hxx
Note that this error was not triggered by running the examples with `display` option.
> Fixed GV display after changes in #911

- unittest/factory/integrator.cpp
- unittest/factory/integrator.hpp
- unittest/test_actions.cpp
- unittest/test_problem.cpp
I've added some unit tests for the RK4 integrator using finite differences. I've checked that all the tests pass. This work is in preparation for a future PR introducing control parametrizations to handle polynomial control trajectories inside an integration step.
> RK4 unittests

- CMakeLists.txt
> [cmake] use OPTION to set BUILD_TESTING

- benchmark/read_csv.py
- examples/notebooks/introduction_to_crocoddyl.ipynb
Copy of #971 with the unreleased code removed
> [example] Updated jupyter notebook

- bindings/python/crocoddyl/core/optctrl/shooting.cpp
- include/crocoddyl/core/optctrl/shooting.hpp
- include/crocoddyl/core/optctrl/shooting.hxx
- include/crocoddyl/core/solver-base.hpp
- include/crocoddyl/core/solvers/box-ddp.hpp
- include/crocoddyl/core/solvers/box-fddp.hpp
- include/crocoddyl/core/solvers/ddp.hpp
- src/core/solver-base.cpp
- src/core/solvers/box-ddp.cpp
- src/core/solvers/box-fddp.cpp
- src/core/solvers/ddp.cpp
- src/core/solvers/fddp.cpp
- src/core/solvers/kkt.cpp
This PR avoids to define matrix/vectors that depend on control using `nu_max`.
It also helps to remove "hard-to-read" code due to the block operations needed with previous approach.
> Introduced the notion of resizeData in solvers

- include/crocoddyl/core/solvers/ddp.hpp
- src/core/solvers/fddp.cpp
Possible solution to https://github.com/loco-3d/crocoddyl/issues/1022
> Update doc for dx_ size

- bindings/python/crocoddyl/core/core.cpp
- bindings/python/crocoddyl/core/core.hpp
- bindings/python/crocoddyl/core/residuals/joint-effort.cpp
- include/crocoddyl/core/fwd.hpp
- include/crocoddyl/core/residuals/joint-acceleration.hpp
- include/crocoddyl/core/residuals/joint-effort.hpp
- include/crocoddyl/core/residuals/joint-effort.hxx
- unittest/test_contacts.cpp
In the previous merged pull #1101, I forgot to renamed the data appropriately. There are also a few extra fixes in the documentation.
> Renamed the data using joint effort as well

- bindings/python/crocoddyl/utils/__init__.py
- unittest/bindings/test_actions.py
This PR fixes some bugs in the python class IAMEulerDerived and adds the corresponding unittest.
> Fix IAMEulerDerived and adding unittest

- bindings/python/crocoddyl/core/action-base.cpp
- bindings/python/crocoddyl/core/diff-action-base.cpp
- include/crocoddyl/core/action-base.hpp
- include/crocoddyl/core/action-base.hxx
- include/crocoddyl/core/diff-action-base.hpp
- include/crocoddyl/core/diff-action-base.hxx
> Enable setting of constraint bounds in Python

- CHANGELOG.md
- include/crocoddyl/multibody/actions/impulse-fwddyn.hxx
Improved efficiency as suggested in https://github.com/loco-3d/crocoddyl/issues/638.
> Replaced selfadjointView to enhace efficiency

- CHANGELOG.md
- include/crocoddyl/core/actions/diff-lqr.hxx
- include/crocoddyl/core/actions/lqr.hxx
This PR fixes the reported issues in https://github.com/loco-3d/crocoddyl/issues/1349.
Fyi @jorisv
> Fixed checking of positive semi-define condition in LQR problems

- CHANGELOG.md
- bindings/python/crocoddyl/CMakeLists.txt
This PR aims at fixing this issue: https://github.com/loco-3d/crocoddyl/issues/1368
> Bugfix: Fix CMake error message during `python_build`

- .github/workflows/conda-ci.yml
- CMakeLists.txt
- include/crocoddyl/core/fwd.hpp
This PR enables ubuntu-latest jobs, evaluates the possibility of compiling with all Github cores, and removes debug symbols for faster compilation in our jobs.
Depending on the results, I might decide to make adjustments.
> Conda CI improvements
